<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DynamicArray.cs" />
    <Compile Include="DoublyLinkedList.cs" />
    <Compile Include="IQueue.cs" />
    <Compile Include="IStack.cs" />
    <Compile Include="LinkedList.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Queue.cs" />
    <Compile Include="Stack.cs" />
  </ItemGroup>

</Project>
